### ISSUE TITLE
Trajectory Estimator segfault

### ISSUE THREAD

**Issue by allai5** [hovren/kontiki_example#1]
Hi, I'm trying to follow your Jupyter notebook tutorial walkthrough, but I am running into a segfault with the solve function of the Trajectory Estimator at `result = estimator.solve(max_iterations=30) ` in the 15th entry of the notebook.

My intermediate stdout output is exactly the same, so I'm wondering if this is a versioning issue with some of the packages being used.

I'm using Python 3.6.9, h5py 3.1.0, the Python wheel for Kontiki on the documentation website (I changed all the `dataset.value` lines to `dataset[()]` in the package manually since it has become deprecated with h5py 1.0), and Ceres 1.14.0.

Below is a backtrace of the segfault:
![image](https://user-images.githubusercontent.com/12412799/112162526-866ae200-8bc2-11eb-86ee-e5f827ae6371.png)

**Comment by hovren** [comment]
My guess would be that the wheel might be incompatible with some off your
host libraries. My guess would be Ceres or Eugene since these are usually
the problem.
I should probably not have provided a wheel in the first place since I
don't have time to test it regularly  :(

Building from source should work and is not particularly difficult. Try
that and get back to me if you run into any problems.

Den tis 23 mars 2021 15:29Alice Lai ***@***.***> skrev:

**Comment by allai5** [comment]
Hi,
Thanks for the reply!

Unfortunately I'm unable to build it from source. It says that it `cannot import name 'trajectory_estimator' ` when trying to `import kontiki` in a Python script.

**Comment by hovren** [comment]
Can you please tell me what operating system and version you used, and what
steps you performed to build and test?

And also please give me the exact error you got with the full traceback.

Den ons 24 mars 2021 05:42Alice Lai ***@***.***> skrev:

**Comment by allai5** [comment]
Hi,
Sorry for the delay, but I managed to fixed the issue! Building from source with Kontiki with Ceres 1.14 fixed it. Thanks for the help :)
